services:
  nakama:
    build:
      context: ..
      dockerfile: Dockerfile
      pull: false
    container_name: ${NAKAMA_NAME}
    restart: unless-stopped
    environment:
      RELEASE_VERSION: ${RELEASE_VERSION}
    entrypoint:
      - "/bin/sh"
      - "-ecx"
      - >
        /nakama/nakama migrate up --database.address ${DATABASE_ADDRESS} &&
        exec /nakama/nakama
        --name ${NAKAMA_NAME}
        --database.address ${DATABASE_ADDRESS}
        --config /nakama/data/nakama.yml
    ports:
      - "${NAKAMA_GRPC_PORT}:7349"
      - "${NAKAMA_HTTP_PORT}:7350"
      - "${NAKAMA_CONSOLE_PORT}:7351"
    volumes:
      - ./nakama.yml:/nakama/data/nakama.yml:ro
      - ../Config:/nakama/data/modules/runtime/Config:ro
    networks:
      - nakama_shared

networks:
  nakama_shared:
    external: true
    name: nakama_shared
